### ISSUE TITLE
GetCertificate error: InvalidChangeBatch when calling the ChangeResourceRecordSets operation: ...but it already exists

### ISSUE THREAD

**Issue by BastLeblanc** [dirkvandooren/AWS_FoundryVTT#2]
I have this error in the custom lambda GetCertificate, ever seen this? ideas to fix this?

`[ERROR] InvalidChangeBatch: An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [Tried to create resource record set [name='_b62bdeb2fxxxxxmanage-www.foundry.HIDDEN.com.', type='CNAME'] but it already exists]
Traceback (most recent call last):
  File "/var/task/index.py", line 20, in lambda_handler
    r53.change_resource_record_sets(
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)`

**Comment by BastLeblanc** [comment]
update, I think it's because it was a second run (after a 1st failure for another reason).
The certificate doesn't get deleted when the stack is deleted.

I made a dirty hack
`diff --git a/template.yml b/template.yml
index 56a208f..fd4bd94 100644
--- a/template.yml
+++ b/template.yml
@@ -674,7 +674,7 @@ Resources:
               ChangeBatch={
                   'Changes': [
                       {
-                          'Action': 'CREATE',
+                          'Action': 'UPSERT',^M
                           'ResourceRecordSet': {
                               'Name': record['ResourceRecord']['Name'],
                               'Type': record['ResourceRecord']['Type'],
  `
But would be cleaner to delete the certificate with the cfn deletion

**Comment by dirkvandooren** [comment]
@BastLeblanc Thanks for the feedback, love the workaround and you are right, shouldn't be needed in the first place.
